using Kingmaker;
using Kingmaker.Blueprints;
using Kingmaker.Blueprints.JsonSystem;
using Kingmaker.Blueprints.Root;
using Kingmaker.Localization;
using Kingmaker.Sound;
using Kingmaker.Visual.Sound;
using UnityEngine;
using static UnityModManagerNet.UnityModManager;

namespace PC_Female_BG_Viconia;

public static class Main {
	internal static Harmony HarmonyInstance;
	internal static ModEntry.ModLogger log;
	internal static ModEntry modEntry;

	public static bool Load(ModEntry modEntry)
	{
		Main.modEntry = modEntry;
		log = modEntry.Logger;
		HarmonyInstance = new Harmony(modEntry.Info.Id);
		HarmonyInstance.PatchAll(Assembly.GetExecutingAssembly());
		return true;
	}

	public static void LogDebug(string message)
	{
#if DEBUG
			log.Log($"DEBUG: {message}");
#endif
	}

	[HarmonyPatch]
	public static class Soundbanks {
		[HarmonyPatch(typeof(AkAudioService), nameof(AkAudioService.Initialize))]
		[HarmonyPostfix]
		public static void AddBankPaths()
		{
			var banksPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
			AkSoundEngine.AddBasePath(banksPath);
		}

		const string PreviewName = "PC_Female_BG_Viconia_Test";
		static readonly uint TestEventId = AkSoundEngine.GetIDFromString(PreviewName);

		[HarmonyPatch(typeof(UnitAsksComponent), nameof(UnitAsksComponent.PlayPreview))]
		[HarmonyPrefix]
		static bool LoadPreviewBank(UnitAsksComponent __instance)
		{
			if (__instance.PreviewSound is not PreviewName)
				return true;

			if (!SoundBanksManager.s_Handles.Any(handle => handle.Key is PreviewName))
				SoundBanksManager.LoadBankSync(PreviewName);

			GameObject gameObject = Game.Instance.UI.Common.gameObject;
			SoundEventsManager.PostEvent(TestEventId, gameObject);

			return false;
		}

		[HarmonyPatch(typeof(BlueprintsCache), nameof(BlueprintsCache.Init))]
		[HarmonyPostfix]
		static void AddAsksListBlueprint()
		{
			// Initialise the ModMenu settings.
			ModMenuSettings.Init();

			LocalizationManager.CurrentPack.PutString("PC_Female_BG_Viconia", "Viconia DeVir");

			var blueprint = new BlueprintUnitAsksList
			{
				// Every mod requires its own unique GUID. Autogenerated on template creation.
				AssetGuid = new(Guid.Parse("e11fff48793b4400940132622f863fd1")),
				name = "PC_Female_BG_Viconia_Barks",
				DisplayName = new() { m_Key = "PC_Female_BG_Viconia" }
			};

			blueprint.ComponentsArray =
			[
				new UnitAsksComponent()
			{
				OwnerBlueprint = blueprint,

				SoundBanks = [ "PC_Female_BG_Viconia_GVR_ENG" ],
				PreviewSound = "PC_Female_BG_Viconia_Test",
				Aggro = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CombatStart_01",
							RandomWeight = 0.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CombatStart_02",
							RandomWeight = 0.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CombatStart_03",
							RandomWeight = 0.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = true,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				Pain = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Pain",
							RandomWeight = 0.0f,
							ExcludeTime = 0,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 2.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				Fatigue = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Fatigue",
							RandomWeight = 0.0f,
							ExcludeTime = 0,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 60.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				Death = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Death",
							RandomWeight = 0.0f,
							ExcludeTime = 0,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = true,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				Unconscious = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Unconscious",
							RandomWeight = 0.0f,
							ExcludeTime = 0,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = true,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				LowHealth = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_LowHealth_01",
							RandomWeight = 0.0f,
							ExcludeTime = 1,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_LowHealth_02",
							RandomWeight = 0.0f,
							ExcludeTime = 1,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 10.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				CriticalHit = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CharCrit_01",
							RandomWeight = 0.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CharCrit_02",
							RandomWeight = 0.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CharCrit_03",
							RandomWeight = 0.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 0.7f,
					ShowOnScreen = false
				},
				Order = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_AttackOrder_01",
							RandomWeight = 0.0f,
							ExcludeTime = 3,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_AttackOrder_02",
							RandomWeight = 0.0f,
							ExcludeTime = 3,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_AttackOrder_03",
							RandomWeight = 0.0f,
							ExcludeTime = 3,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_AttackOrder_04",
							RandomWeight = 0.0f,
							ExcludeTime = 3,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				OrderMove = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Move_01",
							RandomWeight = 0.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Move_02",
							RandomWeight = 0.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Move_03",
							RandomWeight = 0.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Move_04",
							RandomWeight = 0.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Move_05",
							RandomWeight = 0.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Move_06",
							RandomWeight = 0.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Move_07",
							RandomWeight = 0.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = ModMenuSettings.GetMoveCooldown(), // Default Cooldown value is 10s. Make it user-adjustable from 0-120s instead of fixed.
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = ModMenuSettings.GetMoveChance(), // Default Chance value is 10%. Make it user-adjustable from 0-100% instead of fixed.
					ShowOnScreen = false
				},
				Selected = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Select_01",
							RandomWeight = 1.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Select_02",
							RandomWeight = 1.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Select_03",
							RandomWeight = 1.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Select_04",
							RandomWeight = 1.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Select_05",
							RandomWeight = 1.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Select_06",
							RandomWeight = 1.0f,
							ExcludeTime = 4,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_SelectJoke",
							RandomWeight = 0.1f,
							ExcludeTime = 30,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				RefuseEquip = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CantEquip_01",
							RandomWeight = 1.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CantEquip_02",
							RandomWeight = 1.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = true,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				RefuseCast = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CantCast",
							RandomWeight = 0.0f,
							ExcludeTime = 1,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = true,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				CheckSuccess = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CheckSuccess_01",
							RandomWeight = 1.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CheckSuccess_02",
							RandomWeight = 1.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				CheckFail = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CheckFail_01",
							RandomWeight = 1.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_CheckFail_02",
							RandomWeight = 1.0f,
							ExcludeTime = 2,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				RefuseUnequip = new()
				{
					Entries = [],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				Discovery = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Discovery_01",
							RandomWeight = 0.0f,
							ExcludeTime = 1,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						},
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_Discovery_02",
							RandomWeight = 0.0f,
							ExcludeTime = 1,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				Stealth = new()
				{
					Entries =
					[
						new()
						{
							Text = null,
							AkEvent = "PC_Female_BG_Viconia_StealthMode",
							RandomWeight = 1.0f,
							ExcludeTime = 1,
							m_RequiredFlags = [],
							m_ExcludedFlags = [],
							m_RequiredEtudes = null,
							m_ExcludedEtudes = null
						}
					],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				StormRain = new()
				{
					Entries = [],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				StormSnow = new()
				{
					Entries = [],
					Cooldown = 0.0f,
					InterruptOthers = false,
					DelayMin = 0.0f,
					DelayMax = 0.0f,
					Chance = 1.0f,
					ShowOnScreen = false
				},
				AnimationBarks =
				[
					new()
					{
						Entries =
						[
							new()
							{
								Text = null,
								AkEvent = "PC_Female_BG_Viconia_AttackShort",
								RandomWeight = 0.0f,
								ExcludeTime = 0,
								m_RequiredFlags = [],
								m_ExcludedFlags = [],
								m_RequiredEtudes = null,
								m_ExcludedEtudes = null
							}
						],
						Cooldown = 0.0f,
						InterruptOthers = false,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 0.7f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.AttackShort
					},
					new()
					{
						Entries =
						[
							new()
							{
								Text = null,
								AkEvent = "PC_Female_BG_Viconia_CoupDeGrace",
								RandomWeight = 0.0f,
								ExcludeTime = 0,
								m_RequiredFlags = [],
								m_ExcludedFlags = [],
								m_RequiredEtudes = null,
								m_ExcludedEtudes = null
							}
						],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.CoupDeGrace
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.Cast
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.CastDirect
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.CastLong
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.CastShort
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.CastTouch
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.CastYourself
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.Omnicast
					},
					new()
					{
						Entries = [],
						Cooldown = 0.0f,
						InterruptOthers = true,
						DelayMin = 0.0f,
						DelayMax = 0.0f,
						Chance = 1.0f,
						ShowOnScreen = false,
						AnimationEvent = MappedAnimationEventType.Precast
					},
				],
			},
			];

				ResourcesLibrary.BlueprintsCache.AddCachedBlueprint(blueprint.AssetGuid, blueprint);

				BlueprintRoot.Instance.CharGen.m_FemaleVoices = BlueprintRoot.Instance.CharGen.m_FemaleVoices
					.Append(blueprint.ToReference<BlueprintUnitAsksListReference>())
					.ToArray();
		}
	}
}
